import type { Metadata } from "next";
import "./globals.css";
import BottomNavBar from '/home/nikitagregusova@s.zochova.sk/Dokumenty/dev/prve/src/components/BottomNavBar.tsx';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <body>
        {children}
        <BottomNavBar />
      </body>
    </html>
  );
}
